name = "RedefStructs"
uuid = "91f8d46f-6a72-421b-a56e-b73459bd5e0a"
authors = ["Federico Stra <stra.federico@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
